[package]
name = "if-changed"
version = "0.3.9"
edition = "2021"
rust-version = "1.87"
description = "A pre-submit for file changes."
license = "Apache-2.0"
authors = ["Mathematic Inc"]
repository = "https://github.com/mathematic-inc/if-changed"
categories = ["command-line-utilities", "development-tools", "filesystem"]
keywords = ["ci", "git", "hooks", "pre-submit", "presubmit"]

[lib]
path = "if-changed.rs"

[[bin]]
name = "if-changed"
path = "bin/if-changed.rs"

[dependencies]
bstr = "1.13.1"
clap = { version = "4.6.6", features = ["derive", "env"] }
genawaiter = "0.99.1"
git2 = "0.21.0"

[dev-dependencies]
indoc = "2.0.7"
insta = { version = "1.48", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
tempfile = "3.27.0"
