name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@6ccd57f4c5d15bdc2fef309bd9fb6cc9db2ef1c6
      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
