name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b6849436894e144dbce29d7d7fda2ae3bf9d8365
      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
