name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@2d7d9f7ff5b310f983d059b68785b3c74d8b8edd
      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CRATES_IO_TOKEN }}
